### PR TITLE
Added Altair GraphQL Client to GraphQL tools list

### PR DESCRIPTION
**Pull request by imolorhe**
Added a new section for GraphQL tools that support the multipart request spec, and added [Altair](https://altair.sirmuel.design/) to the list.

### CODE REVIEW

**Comment by jaydenseric** [comment]
Awesome, thanks for the PR ❤️

I've moved it into the "Client" section, since Alitair is a GraphQL client, and linked the [`altair-static`](https://npm.im/altair-static) npm package since that is what contains the actual implementation code.

**Comment by imolorhe** [comment]
It is not exactly a "client" as you would use the other clients within your application 😄 It's more an IDE for developing/running your GraphQL queries. It's more in line with GraphiQL and GraphQL Playground.

**Comment by jaydenseric** [comment]
GraphiQL and GraphQL Playground are GraphQL clients too. In relation to this spec, a "client" is the code sending a GraphQL multipart request and a "server" is code that receives and processes a request.

The target audience for the "Implementations" section is people trying to implement the spec themself to make either in a client or server related package. It is useful for them to be able to refer to source and published code for other packages in their chosen language.

**Comment by imolorhe** [comment]
Ah right. Gotcha!

**Pull request merged**
